### PR TITLE
refactored formatting in print statements

### PR DESCRIPTION
**Pull request by GitHK**
## What do these changes do?

Fixes ill formatted prints

## Checklist

- [ ] I think the code is well written
- [x] I updated the table of contents (make toc)
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] **Runs in the swarm**
- [ ] If you design a new module, add your user to .github/CODEOWNERS

### CODE REVIEW

**Comment by GitHK** [comment]
> this is a classic :-) ... just as a tip, when i find this case, it is much easier to use `%` instead of f-strings, i.e.
> 
> ```python
> print("My string %s %d", msg, number) # original: does not work
> print("My string %s %d" % (msg, number) ) # OK: easy to automate replacing
> print(f"My string {msg} {number}") # OK: but more difficult to auto-replace
> ```
> 
> PS: BTW I find very funny the name "f-string" ... :-D

The first one actually does not work with print statements, I don't like the second one because it's not readable :anguished:
I prefer the third option.

If you thing about it `f***-string` is perfect. It messes your renaming plugin. 😂

**Comment by sanderegg** [comment]
> Even if the change is so small, you should increase the patch version as well instead of overriding a released existing image!!! Actually, every service should have its own CHANGELOG that the user could check and decide whether he/she wants to update its pipeline
> 
> Would be nice to support all this much more, e.g. CI stops you from overriding existing version or fails if CHANGELOG is missing etc

Actually the CI will stop you from overriding the version. as this will fail in master probably...

**Comment by GitHK** [comment]
@sanderegg I think that in the past I've overwritten the 2.0.0 version, but I agree that it should be bumped on each change.

**Comment by sanderegg** [comment]
> @sanderegg I think that in the past I've overwritten the 2.0.0 version, but I agree that it should be bumped on each change.

Yes but we did previously manually remove it from the registry

**Pull request merged**
